version: '3'
volumes:
  grafana-storage:
  aa-storage:

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./:/var/lib/grafana/plugins/archiverappliance-datasource
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=true

  archappl:
    hostname: archappl
    image: pklaus/archiver-appliance
    ports:
     - "17665:17665"
    volumes:
     - aa-storage:/storage/sts
     - aa-storage:/storage/mts
     - aa-storage:/storage/lts
     - aa-storage:/storage/logs
    stdin_open: true
    tty: true
    #entrypoint: /bin/bash /opt/archappl/scripts/start.sh
    environment:
      ARCHAPPL_ALL_APPS_ON_ONE_JVM: "true"
      #EPICS_CA_ADDR_LIST: "127.0.0.1"
      #EPICS_CA_AUTO_ADDR_LIST: "no"
      ARCHAPPL_PERSISTENCE_LAYER: "org.epics.archiverappliance.config.persistence.RedisPersistence"
      ARCHAPPL_PERSISTENCE_LAYER_REDISURL: "redis-db"
    depends_on:
     - redis-db
    links: 
     - redis-db
     - example-ioc

  redis-db:
    image: redis
    volumes:
      - aa-storage:/data
    command: redis-server --appendonly yes

  example-ioc:
    image: pklaus/epics_base:7.0.2.2_debian
    stdin_open: true
    tty: true
    working_dir: /epics/iocs/example/iocBoot/iocEXAMPLE
    expose:
      - "5064-5065/udp"
      - "5064-5065"
    restart: always
    command: ./st.cmd